-- Migration 008: full make catalogue
--
-- Why: the selector opened on 18 makes, so a user whose car was not one of
-- them had nowhere to go — the list was the wall, not the search. The set below
-- mirrors the make list used by list.am, the marketplace this audience already
-- knows, so the brand a person is looking for is present under the spelling
-- they expect.
--
-- Cyrillic-era brands keep list.am's own labelling (`IZH (ИЖ)`) rather than a
-- transliteration of our choosing, so search works from either alphabet.
--
-- ВАЗ / ГАЗ / УАЗ are already in the catalogue in Cyrillic and are deliberately
-- NOT repeated here as `VAZ (Lada)` / `GAZ (ГАЗ)` / `UAZ (УАЗ)` — the name guard
-- below compares text, so those would land as visible duplicates.
--
-- Idempotent: guarded by NOT EXISTS on name, so re-running is safe.

INSERT INTO car_makes (name)
SELECT v.name
FROM (VALUES
    ('Abarth'),
    ('Acura'),
    ('Aion'),
    ('AIQAR'),
    ('Aito'),
    ('Alfa Romeo'),
    ('Arcfox'),
    ('Avatr'),
    ('BAIC'),
    ('BAW'),
    ('Bentley'),
    ('Buick'),
    ('BYD'),
    ('Cadillac'),
    ('Changan'),
    ('Chery'),
    ('CheryExeed'),
    ('Chevrolet'),
    ('Chrysler'),
    ('Citroen'),
    ('CMC'),
    ('Dacia'),
    ('Daewoo'),
    ('Daihatsu'),
    ('Datsun'),
    ('Denza'),
    ('Derways'),
    ('DFSK'),
    ('Dodge'),
    ('DongFeng'),
    ('ErAZ'),
    ('Explorer'),
    ('Farizon'),
    ('FAW'),
    ('Ferrari'),
    ('Fiat'),
    ('Fisker'),
    ('Forthing'),
    ('Foton'),
    ('GAC'),
    ('Geely'),
    ('Genesis'),
    ('GMC'),
    ('Great Wall (GWM)'),
    ('Haval'),
    ('Hongqi'),
    ('Hongyang'),
    ('Hozon'),
    ('Hummer'),
    ('iCar'),
    ('IM Motors'),
    ('Infiniti'),
    ('Iran Khodro'),
    ('Isuzu'),
    ('IZH (ИЖ)'),
    ('JAC'),
    ('Jaguar'),
    ('Jeep'),
    ('Jetour'),
    ('Jiyue'),
    ('JMC'),
    ('Karry'),
    ('Lamborghini'),
    ('Lancia'),
    ('Land Rover'),
    ('Leapmotor'),
    ('Lifan'),
    ('Lincoln'),
    ('Livan'),
    ('LiXiang'),
    ('Lotus'),
    ('LuAZ (ЛуАЗ)'),
    ('Lucid'),
    ('Luxeed'),
    ('Lynk & Co'),
    ('Maextro'),
    ('Maserati'),
    ('Maxus'),
    ('McLaren'),
    ('Mercury'),
    ('MG'),
    ('MINI'),
    ('Mitsuoka'),
    ('Moskvich (Москвич)'),
    ('Nio'),
    ('Nysa'),
    ('OKA'),
    ('Oldsmobile'),
    ('Omoda'),
    ('Opel'),
    ('Peugeot'),
    ('Plymouth'),
    ('Polestar'),
    ('Pontiac'),
    ('Porsche'),
    ('RAM'),
    ('Ravon'),
    ('Renault'),
    ('Renault Samsung'),
    ('Riddara'),
    ('Rivian'),
    ('Roewe'),
    ('Rolls-Royce'),
    ('Rover'),
    ('Rox'),
    ('Ruichi'),
    ('Saab'),
    ('Saipa'),
    ('Saturn'),
    ('Scion'),
    ('Seat'),
    ('Sena Motors'),
    ('ShuangHuan'),
    ('Skoda'),
    ('Skywell'),
    ('Smart'),
    ('SMZ'),
    ('SsangYong'),
    ('Suzuki'),
    ('Tesla'),
    ('Triumph'),
    ('Vauxhall'),
    ('VGV'),
    ('VinFast'),
    ('Volvo'),
    ('Voyah'),
    ('Willys'),
    ('Wuling'),
    ('Xiaomi'),
    ('Xpeng'),
    ('ZAZ (ЗАЗ)'),
    ('Zeekr'),
    ('ZIL (ЗИЛ)'),
    ('ZX')
) AS v (name)
WHERE NOT EXISTS (
    SELECT 1 FROM car_makes m WHERE m.name = v.name
);
