-- Migration 010: model catalogue for every make
--
-- Sources, per make, highest precedence first:
--   * hand-curated  — Soviet/CIS, Chinese and Iranian brands, which the
--     open datasets either omit or describe as a US trim list;
--   * car-list (European market) — the right shape for Armenia: it knows
--     Opel Astra and Skoda Octavia, which vPIC does not;
--   * vPIC (NHTSA, free) — US/JP/KR brands.
--
-- list.am was the requested source but blocks automated access, so its
-- catalogue could not be read; the sets below were assembled instead.
--
-- Makes still without models are left empty on purpose: inventing a model
-- name would let someone pick a car that does not exist and then shop for
-- its parts. The generation step is skippable, so a make with models
-- completes the wizard even with no generations recorded.
-- Left empty (6): VGV, AIQAR, Sena Motors, Hongyang, Ruichi, Farizon
--
-- Idempotent: guarded by NOT EXISTS on (make, lower(name)).

INSERT INTO car_models (make_id, name)
SELECT mk.id, m.name
FROM (VALUES
    ('ВАЗ', '2101'),
    ('ВАЗ', '2105'),
    ('ВАЗ', '2106'),
    ('ВАЗ', '2107'),
    ('ВАЗ', '2108'),
    ('ВАЗ', '2109'),
    ('ВАЗ', '2110'),
    ('ВАЗ', '2112'),
    ('ВАЗ', '2114'),
    ('ВАЗ', '2115'),
    ('ВАЗ', 'Приора'),
    ('ВАЗ', 'Калина'),
    ('ВАЗ', 'Гранта'),
    ('ВАЗ', 'Веста'),
    ('ВАЗ', 'Ларгус'),
    ('ВАЗ', 'Нива'),
    ('ВАЗ', 'Нива Тревел'),
    ('ВАЗ', 'XRAY'),
    ('ВАЗ', '4x4'),
    ('ГАЗ', 'Волга'),
    ('ГАЗ', 'Газель'),
    ('ГАЗ', 'Газель Next'),
    ('ГАЗ', 'Соболь'),
    ('ГАЗ', 'ГАЗон Next'),
    ('ГАЗ', '3307'),
    ('ГАЗ', '66'),
    ('ГАЗ', '24'),
    ('ГАЗ', '31105'),
    ('УАЗ', 'Патриот'),
    ('УАЗ', 'Хантер'),
    ('УАЗ', 'Пикап'),
    ('УАЗ', 'Профи'),
    ('УАЗ', 'Буханка (2206)'),
    ('УАЗ', '469'),
    ('УАЗ', '3151'),
    ('УАЗ', '3303'),
    ('Toyota', '4-Runner'),
    ('Toyota', 'Auris'),
    ('Toyota', 'Avensis'),
    ('Toyota', 'Avensis Combi'),
    ('Toyota', 'Avensis Van Verso'),
    ('Toyota', 'Aygo'),
    ('Toyota', 'Camry'),
    ('Toyota', 'Carina'),
    ('Toyota', 'Celica'),
    ('Toyota', 'Corolla'),
    ('Toyota', 'Corolla Combi'),
    ('Toyota', 'Corolla sedan'),
    ('Toyota', 'Corolla Verso'),
    ('Toyota', 'FJ Cruiser'),
    ('Toyota', 'GT86'),
    ('Toyota', 'Hiace'),
    ('Toyota', 'Hiace Van'),
    ('Toyota', 'Highlander'),
    ('Toyota', 'Hilux'),
    ('Toyota', 'Land Cruiser'),
    ('Toyota', 'MR2'),
    ('Toyota', 'Paseo'),
    ('Toyota', 'Picnic'),
    ('Toyota', 'Prius'),
    ('Toyota', 'RAV4'),
    ('Toyota', 'Sequoia'),
    ('Toyota', 'Starlet'),
    ('Toyota', 'Supra'),
    ('Toyota', 'Tundra'),
    ('Toyota', 'Urban Cruiser'),
    ('Toyota', 'Verso'),
    ('Toyota', 'Yaris'),
    ('Toyota', 'Yaris Verso'),
    ('Hyundai', 'Accent'),
    ('Hyundai', 'Atos'),
    ('Hyundai', 'Atos Prime'),
    ('Hyundai', 'Coupé'),
    ('Hyundai', 'Elantra'),
    ('Hyundai', 'Galloper'),
    ('Hyundai', 'Genesis'),
    ('Hyundai', 'Getz'),
    ('Hyundai', 'Grandeur'),
    ('Hyundai', 'H 350'),
    ('Hyundai', 'H1'),
    ('Hyundai', 'H1 Bus'),
    ('Hyundai', 'H1 Van'),
    ('Hyundai', 'H200'),
    ('Hyundai', 'i10'),
    ('Hyundai', 'i20'),
    ('Hyundai', 'i30'),
    ('Hyundai', 'i30 CW'),
    ('Hyundai', 'i40'),
    ('Hyundai', 'i40 CW'),
    ('Hyundai', 'ix20'),
    ('Hyundai', 'ix35'),
    ('Hyundai', 'ix55'),
    ('Hyundai', 'Lantra'),
    ('Hyundai', 'Matrix'),
    ('Hyundai', 'Santa Fe'),
    ('Hyundai', 'Sonata'),
    ('Hyundai', 'Terracan'),
    ('Hyundai', 'Trajet'),
    ('Hyundai', 'Tucson'),
    ('Hyundai', 'Veloster'),
    ('Kia', 'Avella'),
    ('Kia', 'Besta'),
    ('Kia', 'Carens'),
    ('Kia', 'Carnival'),
    ('Kia', 'Cee`d'),
    ('Kia', 'Cee`d SW'),
    ('Kia', 'Cerato'),
    ('Kia', 'K 2500'),
    ('Kia', 'Magentis'),
    ('Kia', 'Opirus'),
    ('Kia', 'Optima'),
    ('Kia', 'Picanto'),
    ('Kia', 'Pregio'),
    ('Kia', 'Pride'),
    ('Kia', 'Pro Cee`d'),
    ('Kia', 'Rio'),
    ('Kia', 'Rio Combi'),
    ('Kia', 'Rio sedan'),
    ('Kia', 'Sephia'),
    ('Kia', 'Shuma'),
    ('Kia', 'Sorento'),
    ('Kia', 'Soul'),
    ('Kia', 'Sportage'),
    ('Kia', 'Venga'),
    ('Mercedes-Benz', '100 D'),
    ('Mercedes-Benz', '115'),
    ('Mercedes-Benz', '124'),
    ('Mercedes-Benz', '126'),
    ('Mercedes-Benz', '190'),
    ('Mercedes-Benz', '190 D'),
    ('Mercedes-Benz', '190 E'),
    ('Mercedes-Benz', '200 - 300'),
    ('Mercedes-Benz', '200 D'),
    ('Mercedes-Benz', '200 E'),
    ('Mercedes-Benz', '210 Van'),
    ('Mercedes-Benz', '210 kombi'),
    ('Mercedes-Benz', '310 Van'),
    ('Mercedes-Benz', '310 kombi'),
    ('Mercedes-Benz', '230 - 300 CE Coupé'),
    ('Mercedes-Benz', '260 - 560 SE'),
    ('Mercedes-Benz', '260 - 560 SEL'),
    ('Mercedes-Benz', '500 - 600 SEC Coupé'),
    ('Mercedes-Benz', 'Trieda A'),
    ('Mercedes-Benz', 'A'),
    ('Mercedes-Benz', 'A L'),
    ('Mercedes-Benz', 'AMG GT'),
    ('Mercedes-Benz', 'Trieda B'),
    ('Mercedes-Benz', 'Trieda C'),
    ('Mercedes-Benz', 'C'),
    ('Mercedes-Benz', 'C Sportcoupé'),
    ('Mercedes-Benz', 'C T'),
    ('Mercedes-Benz', 'Citan'),
    ('Mercedes-Benz', 'CL'),
    ('Mercedes-Benz', 'CLA'),
    ('Mercedes-Benz', 'CLC'),
    ('Mercedes-Benz', 'CLK Cabrio'),
    ('Mercedes-Benz', 'CLK Coupé'),
    ('Mercedes-Benz', 'CLS'),
    ('Mercedes-Benz', 'Trieda E'),
    ('Mercedes-Benz', 'E'),
    ('Mercedes-Benz', 'E Cabrio'),
    ('Mercedes-Benz', 'E Coupé'),
    ('Mercedes-Benz', 'E T'),
    ('Mercedes-Benz', 'Trieda G'),
    ('Mercedes-Benz', 'G Cabrio'),
    ('Mercedes-Benz', 'GL'),
    ('Mercedes-Benz', 'GLA'),
    ('Mercedes-Benz', 'GLC'),
    ('Mercedes-Benz', 'GLE'),
    ('Mercedes-Benz', 'GLK'),
    ('Mercedes-Benz', 'Trieda M'),
    ('Mercedes-Benz', 'MB 100'),
    ('Mercedes-Benz', 'Trieda R'),
    ('Mercedes-Benz', 'Trieda S'),
    ('Mercedes-Benz', 'S'),
    ('Mercedes-Benz', 'S Coupé'),
    ('Mercedes-Benz', 'SL'),
    ('Mercedes-Benz', 'SLC'),
    ('Mercedes-Benz', 'SLK'),
    ('Mercedes-Benz', 'SLR'),
    ('Mercedes-Benz', 'Sprinter'),
    ('BMW', 'i3'),
    ('BMW', 'i8'),
    ('BMW', 'M3'),
    ('BMW', 'M4'),
    ('BMW', 'M5'),
    ('BMW', 'M6'),
    ('BMW', 'Rad 1'),
    ('BMW', 'Rad 1 Cabrio'),
    ('BMW', 'Rad 1 Coupé'),
    ('BMW', 'Rad 2'),
    ('BMW', 'Rad 2 Active Tourer'),
    ('BMW', 'Rad 2 Coupé'),
    ('BMW', 'Rad 2 Gran Tourer'),
    ('BMW', 'Rad 3'),
    ('BMW', 'Rad 3 Cabrio'),
    ('BMW', 'Rad 3 Compact'),
    ('BMW', 'Rad 3 Coupé'),
    ('BMW', 'Rad 3 GT'),
    ('BMW', 'Rad 3 Touring'),
    ('BMW', 'Rad 4'),
    ('BMW', 'Rad 4 Cabrio'),
    ('BMW', 'Rad 4 Gran Coupé'),
    ('BMW', 'Rad 5'),
    ('BMW', 'Rad 5 GT'),
    ('BMW', 'Rad 5 Touring'),
    ('BMW', 'Rad 6'),
    ('BMW', 'Rad 6 Cabrio'),
    ('BMW', 'Rad 6 Coupé'),
    ('BMW', 'Rad 6 Gran Coupé'),
    ('BMW', 'Rad 7'),
    ('BMW', 'Rad 8 Coupé'),
    ('BMW', 'X1'),
    ('BMW', 'X3'),
    ('BMW', 'X4'),
    ('BMW', 'X5'),
    ('BMW', 'X6'),
    ('BMW', 'Z3'),
    ('BMW', 'Z3 Coupé'),
    ('BMW', 'Z3 Roadster'),
    ('BMW', 'Z4'),
    ('BMW', 'Z4 Roadster'),
    ('Volkswagen', 'Amarok'),
    ('Volkswagen', 'Beetle'),
    ('Volkswagen', 'Bora'),
    ('Volkswagen', 'Bora Variant'),
    ('Volkswagen', 'Caddy'),
    ('Volkswagen', 'Caddy Van'),
    ('Volkswagen', 'Life'),
    ('Volkswagen', 'California'),
    ('Volkswagen', 'Caravelle'),
    ('Volkswagen', 'CC'),
    ('Volkswagen', 'Crafter'),
    ('Volkswagen', 'Crafter Van'),
    ('Volkswagen', 'Crafter Kombi'),
    ('Volkswagen', 'CrossTouran'),
    ('Volkswagen', 'Eos'),
    ('Volkswagen', 'Fox'),
    ('Volkswagen', 'Golf'),
    ('Volkswagen', 'Golf Cabrio'),
    ('Volkswagen', 'Golf Plus'),
    ('Volkswagen', 'Golf Sportvan'),
    ('Volkswagen', 'Golf Variant'),
    ('Volkswagen', 'Jetta'),
    ('Volkswagen', 'LT'),
    ('Volkswagen', 'Lupo'),
    ('Volkswagen', 'Multivan'),
    ('Volkswagen', 'New Beetle'),
    ('Volkswagen', 'New Beetle Cabrio'),
    ('Volkswagen', 'Passat'),
    ('Volkswagen', 'Passat Alltrack'),
    ('Volkswagen', 'Passat CC'),
    ('Volkswagen', 'Passat Variant'),
    ('Volkswagen', 'Passat Variant Van'),
    ('Volkswagen', 'Phaeton'),
    ('Volkswagen', 'Polo'),
    ('Volkswagen', 'Polo Van'),
    ('Volkswagen', 'Polo Variant'),
    ('Volkswagen', 'Scirocco'),
    ('Volkswagen', 'Sharan'),
    ('Volkswagen', 'T4'),
    ('Volkswagen', 'T4 Caravelle'),
    ('Volkswagen', 'T4 Multivan'),
    ('Volkswagen', 'T5'),
    ('Volkswagen', 'T5 Caravelle'),
    ('Volkswagen', 'T5 Multivan'),
    ('Volkswagen', 'T5 Transporter Shuttle'),
    ('Volkswagen', 'Tiguan'),
    ('Volkswagen', 'Touareg'),
    ('Volkswagen', 'Touran'),
    ('Nissan', '100 NX'),
    ('Nissan', '200 SX'),
    ('Nissan', '350 Z'),
    ('Nissan', '350 Z Roadster'),
    ('Nissan', '370 Z'),
    ('Nissan', 'Almera'),
    ('Nissan', 'Almera Tino'),
    ('Nissan', 'Cabstar E - T'),
    ('Nissan', 'Cabstar TL2 Valnik'),
    ('Nissan', 'e-NV200'),
    ('Nissan', 'GT-R'),
    ('Nissan', 'Insterstar'),
    ('Nissan', 'Juke'),
    ('Nissan', 'King Cab'),
    ('Nissan', 'Leaf'),
    ('Nissan', 'Maxima'),
    ('Nissan', 'Maxima QX'),
    ('Nissan', 'Micra'),
    ('Nissan', 'Murano'),
    ('Nissan', 'Navara'),
    ('Nissan', 'Note'),
    ('Nissan', 'NP300 Pickup'),
    ('Nissan', 'NV200'),
    ('Nissan', 'NV400'),
    ('Nissan', 'Pathfinder'),
    ('Nissan', 'Patrol'),
    ('Nissan', 'Patrol GR'),
    ('Nissan', 'Pickup'),
    ('Nissan', 'Pixo'),
    ('Nissan', 'Primastar'),
    ('Nissan', 'Primastar Combi'),
    ('Nissan', 'Primera'),
    ('Nissan', 'Primera Combi'),
    ('Nissan', 'Pulsar'),
    ('Nissan', 'Qashqai'),
    ('Nissan', 'Serena'),
    ('Nissan', 'Sunny'),
    ('Nissan', 'Terrano'),
    ('Nissan', 'Tiida'),
    ('Nissan', 'Trade'),
    ('Nissan', 'Vanette Cargo'),
    ('Nissan', 'X-Trail'),
    ('Honda', 'Accord'),
    ('Honda', 'Accord Coupé'),
    ('Honda', 'Accord Tourer'),
    ('Honda', 'City'),
    ('Honda', 'Civic'),
    ('Honda', 'Civic Aerodeck'),
    ('Honda', 'Civic Coupé'),
    ('Honda', 'Civic Tourer'),
    ('Honda', 'Civic Type R'),
    ('Honda', 'CR-V'),
    ('Honda', 'CR-X'),
    ('Honda', 'CR-Z'),
    ('Honda', 'FR-V'),
    ('Honda', 'HR-V'),
    ('Honda', 'Insight'),
    ('Honda', 'Integra'),
    ('Honda', 'Jazz'),
    ('Honda', 'Legend'),
    ('Honda', 'Prelude'),
    ('Mitsubishi', '3000 GT'),
    ('Mitsubishi', 'ASX'),
    ('Mitsubishi', 'Carisma'),
    ('Mitsubishi', 'Colt'),
    ('Mitsubishi', 'Colt CC'),
    ('Mitsubishi', 'Eclipse'),
    ('Mitsubishi', 'Fuso canter'),
    ('Mitsubishi', 'Galant'),
    ('Mitsubishi', 'Galant Combi'),
    ('Mitsubishi', 'Grandis'),
    ('Mitsubishi', 'L200'),
    ('Mitsubishi', 'L200 Pick up'),
    ('Mitsubishi', 'L200 Pick up Allrad'),
    ('Mitsubishi', 'L300'),
    ('Mitsubishi', 'Lancer'),
    ('Mitsubishi', 'Lancer Combi'),
    ('Mitsubishi', 'Lancer Evo'),
    ('Mitsubishi', 'Lancer Sportback'),
    ('Mitsubishi', 'Outlander'),
    ('Mitsubishi', 'Pajero'),
    ('Mitsubishi', 'Pajeto Pinin'),
    ('Mitsubishi', 'Pajero Pinin Wagon'),
    ('Mitsubishi', 'Pajero Sport'),
    ('Mitsubishi', 'Pajero Wagon'),
    ('Mitsubishi', 'Space Star'),
    ('Lexus', 'CT'),
    ('Lexus', 'GS'),
    ('Lexus', 'GS 300'),
    ('Lexus', 'GX'),
    ('Lexus', 'IS'),
    ('Lexus', 'IS 200'),
    ('Lexus', 'IS 250 C'),
    ('Lexus', 'IS-F'),
    ('Lexus', 'LS'),
    ('Lexus', 'LX'),
    ('Lexus', 'NX'),
    ('Lexus', 'RC F'),
    ('Lexus', 'RX'),
    ('Lexus', 'RX 300'),
    ('Lexus', 'RX 400h'),
    ('Lexus', 'RX 450h'),
    ('Lexus', 'SC 430'),
    ('Ford', 'Aerostar'),
    ('Ford', 'B-Max'),
    ('Ford', 'C-Max'),
    ('Ford', 'Cortina'),
    ('Ford', 'Cougar'),
    ('Ford', 'Edge'),
    ('Ford', 'Escort'),
    ('Ford', 'Escort Cabrio'),
    ('Ford', 'Escort kombi'),
    ('Ford', 'Explorer'),
    ('Ford', 'F-150'),
    ('Ford', 'F-250'),
    ('Ford', 'Fiesta'),
    ('Ford', 'Focus'),
    ('Ford', 'Focus C-Max'),
    ('Ford', 'Focus CC'),
    ('Ford', 'Focus kombi'),
    ('Ford', 'Fusion'),
    ('Ford', 'Galaxy'),
    ('Ford', 'Grand C-Max'),
    ('Ford', 'Ka'),
    ('Ford', 'Kuga'),
    ('Ford', 'Maverick'),
    ('Ford', 'Mondeo'),
    ('Ford', 'Mondeo Combi'),
    ('Ford', 'Mustang'),
    ('Ford', 'Orion'),
    ('Ford', 'Puma'),
    ('Ford', 'Ranger'),
    ('Ford', 'S-Max'),
    ('Ford', 'Sierra'),
    ('Ford', 'Street Ka'),
    ('Ford', 'Tourneo Connect'),
    ('Ford', 'Tourneo Custom'),
    ('Ford', 'Transit'),
    ('Ford', 'Transit Bus'),
    ('Ford', 'Transit Connect LWB'),
    ('Ford', 'Transit Courier'),
    ('Ford', 'Transit Custom'),
    ('Ford', 'Transit kombi'),
    ('Ford', 'Transit Tourneo'),
    ('Ford', 'Transit Valnik'),
    ('Ford', 'Transit Van'),
    ('Ford', 'Transit Van 350'),
    ('Ford', 'Windstar'),
    ('Mazda', '121'),
    ('Mazda', '2'),
    ('Mazda', '3'),
    ('Mazda', '323'),
    ('Mazda', '323 Combi'),
    ('Mazda', '323 Coupé'),
    ('Mazda', '323 F'),
    ('Mazda', '5'),
    ('Mazda', '6'),
    ('Mazda', '6 Combi'),
    ('Mazda', '626'),
    ('Mazda', '626 Combi'),
    ('Mazda', 'B-Fighter'),
    ('Mazda', 'B2500'),
    ('Mazda', 'BT'),
    ('Mazda', 'CX-3'),
    ('Mazda', 'CX-5'),
    ('Mazda', 'CX-7'),
    ('Mazda', 'CX-9'),
    ('Mazda', 'Demio'),
    ('Mazda', 'MPV'),
    ('Mazda', 'MX-3'),
    ('Mazda', 'MX-5'),
    ('Mazda', 'MX-6'),
    ('Mazda', 'Premacy'),
    ('Mazda', 'RX-7'),
    ('Mazda', 'RX-8'),
    ('Mazda', 'Xedox 6'),
    ('Audi', '100'),
    ('Audi', '100 Avant'),
    ('Audi', '80'),
    ('Audi', '80 Avant'),
    ('Audi', '80 Cabrio'),
    ('Audi', '90'),
    ('Audi', 'A1'),
    ('Audi', 'A2'),
    ('Audi', 'A3'),
    ('Audi', 'A3 Cabriolet'),
    ('Audi', 'A3 Limuzina'),
    ('Audi', 'A3 Sportback'),
    ('Audi', 'A4'),
    ('Audi', 'A4 Allroad'),
    ('Audi', 'A4 Avant'),
    ('Audi', 'A4 Cabriolet'),
    ('Audi', 'A5'),
    ('Audi', 'A5 Cabriolet'),
    ('Audi', 'A5 Sportback'),
    ('Audi', 'A6'),
    ('Audi', 'A6 Allroad'),
    ('Audi', 'A6 Avant'),
    ('Audi', 'A7'),
    ('Audi', 'A8'),
    ('Audi', 'A8 Long'),
    ('Audi', 'Q3'),
    ('Audi', 'Q5'),
    ('Audi', 'Q7'),
    ('Audi', 'R8'),
    ('Audi', 'RS4 Cabriolet'),
    ('Audi', 'RS4/RS4 Avant'),
    ('Audi', 'RS5'),
    ('Audi', 'RS6 Avant'),
    ('Audi', 'RS7'),
    ('Audi', 'S3/S3 Sportback'),
    ('Audi', 'S4 Cabriolet'),
    ('Audi', 'S4/S4 Avant'),
    ('Audi', 'S5/S5 Cabriolet'),
    ('Audi', 'S6/RS6'),
    ('Audi', 'S7'),
    ('Audi', 'S8'),
    ('Audi', 'SQ5'),
    ('Audi', 'TT Coupé'),
    ('Audi', 'TT Roadster'),
    ('Audi', 'TTS'),
    ('Subaru', 'BRZ'),
    ('Subaru', 'Forester'),
    ('Subaru', 'Impreza'),
    ('Subaru', 'Impreza Wagon'),
    ('Subaru', 'Justy'),
    ('Subaru', 'Legacy'),
    ('Subaru', 'Legacy Wagon'),
    ('Subaru', 'Legacy Outback'),
    ('Subaru', 'Levorg'),
    ('Subaru', 'Outback'),
    ('Subaru', 'SVX'),
    ('Subaru', 'Tribeca'),
    ('Subaru', 'Tribeca B9'),
    ('Subaru', 'XV'),
    ('Seat', 'Alhambra'),
    ('Seat', 'Altea'),
    ('Seat', 'Altea XL'),
    ('Seat', 'Arosa'),
    ('Seat', 'Cordoba'),
    ('Seat', 'Cordoba Vario'),
    ('Seat', 'Exeo'),
    ('Seat', 'Ibiza'),
    ('Seat', 'Ibiza ST'),
    ('Seat', 'Exeo ST'),
    ('Seat', 'Leon'),
    ('Seat', 'Leon ST'),
    ('Seat', 'Inca'),
    ('Seat', 'Mii'),
    ('Seat', 'Toledo'),
    ('OKA', '1111'),
    ('BAW', 'BJ40'),
    ('BAW', '212'),
    ('BAW', 'Sasa'),
    ('BAW', 'Luling'),
    ('Wuling', 'Hongguang'),
    ('Wuling', 'Bingo'),
    ('Wuling', 'Almaz'),
    ('Wuling', 'Cortez'),
    ('Wuling', 'Air EV'),
    ('Moskvich (Москвич)', '3'),
    ('Moskvich (Москвич)', '3е'),
    ('Moskvich (Москвич)', '6'),
    ('Moskvich (Москвич)', '8'),
    ('Moskvich (Москвич)', '2140'),
    ('Moskvich (Москвич)', '2141'),
    ('Moskvich (Москвич)', '412'),
    ('Moskvich (Москвич)', '408'),
    ('JAC', 'S3'),
    ('JAC', 'S5'),
    ('JAC', 'S7'),
    ('JAC', 'T6'),
    ('JAC', 'T8'),
    ('JAC', 'J7'),
    ('JAC', 'Sunray'),
    ('JAC', 'iEV7S'),
    ('Lucid', 'Air'),
    ('Lucid', 'Gravity'),
    ('FAW', 'Besturn B50'),
    ('FAW', 'Besturn X80'),
    ('FAW', 'Bestune T77'),
    ('FAW', 'Bestune T99'),
    ('FAW', 'V5'),
    ('FAW', 'Oley'),
    ('Fiat', '1100'),
    ('Fiat', '126'),
    ('Fiat', '500'),
    ('Fiat', '500L'),
    ('Fiat', '500X'),
    ('Fiat', '850'),
    ('Fiat', 'Barchetta'),
    ('Fiat', 'Brava'),
    ('Fiat', 'Cinquecento'),
    ('Fiat', 'Coupé'),
    ('Fiat', 'Croma'),
    ('Fiat', 'Doblo'),
    ('Fiat', 'Doblo Cargo'),
    ('Fiat', 'Doblo Cargo Combi'),
    ('Fiat', 'Ducato'),
    ('Fiat', 'Ducato Van'),
    ('Fiat', 'Ducato Kombi'),
    ('Fiat', 'Ducato Podvozok'),
    ('Fiat', 'Florino'),
    ('Fiat', 'Florino Combi'),
    ('Fiat', 'Freemont'),
    ('Fiat', 'Grande Punto'),
    ('Fiat', 'Idea'),
    ('Fiat', 'Linea'),
    ('Fiat', 'Marea'),
    ('Fiat', 'Marea Weekend'),
    ('Fiat', 'Multipla'),
    ('Fiat', 'Palio Weekend'),
    ('Fiat', 'Panda'),
    ('Fiat', 'Panda Van'),
    ('Fiat', 'Punto'),
    ('Fiat', 'Punto Cabriolet'),
    ('Fiat', 'Punto Evo'),
    ('Fiat', 'Punto Van'),
    ('Fiat', 'Qubo'),
    ('Fiat', 'Scudo'),
    ('Fiat', 'Scudo Van'),
    ('Fiat', 'Scudo Kombi'),
    ('Fiat', 'Sedici'),
    ('Fiat', 'Seicento'),
    ('Fiat', 'Stilo'),
    ('Fiat', 'Stilo Multiwagon'),
    ('Fiat', 'Strada'),
    ('Fiat', 'Talento'),
    ('Fiat', 'Tipo'),
    ('Fiat', 'Ulysse'),
    ('Fiat', 'Uno'),
    ('Fiat', 'X1/9'),
    ('IM Motors', 'L7'),
    ('IM Motors', 'LS7'),
    ('IM Motors', 'LS6'),
    ('IM Motors', 'L6'),
    ('Voyah', 'Free'),
    ('Voyah', 'Dream'),
    ('Voyah', 'Passion'),
    ('Voyah', 'Courage'),
    ('Triumph', 'Adventurer'),
    ('Triumph', 'America'),
    ('Triumph', 'Bobber TFC'),
    ('Triumph', 'Bonneville'),
    ('Triumph', 'Bonneville Bobber'),
    ('Triumph', 'Bonneville Speedmaster'),
    ('Triumph', 'Bonneville T100'),
    ('Triumph', 'Bonneville T120'),
    ('Triumph', 'Daytona'),
    ('Triumph', 'Daytona 1200'),
    ('Triumph', 'Daytona 600'),
    ('Triumph', 'Daytona 650'),
    ('Triumph', 'Daytona 660'),
    ('Triumph', 'Daytona 675'),
    ('Triumph', 'Daytona 675 R'),
    ('Triumph', 'Daytona 900'),
    ('Triumph', 'Daytona Moto2 765'),
    ('Triumph', 'Daytona Super III'),
    ('Triumph', 'Explorer'),
    ('Triumph', 'Legend 750'),
    ('Triumph', 'Legend TT'),
    ('Triumph', 'Rocket 3'),
    ('Triumph', 'Rocket 3 GT'),
    ('Triumph', 'Rocket 3 R'),
    ('Triumph', 'Rocket 3 R/GT'),
    ('Triumph', 'Rocket 3 Storm R/GT'),
    ('Triumph', 'Rocket III'),
    ('Triumph', 'Scrambler'),
    ('Triumph', 'Scrambler 1200 X'),
    ('Triumph', 'Scrambler 1200 XC'),
    ('Triumph', 'Scrambler 1200 XE'),
    ('Triumph', 'Scrambler 400 X'),
    ('Triumph', 'Scrambler 400XC'),
    ('Triumph', 'Scrambler 900'),
    ('Triumph', 'Speed 400'),
    ('Triumph', 'Speed Four'),
    ('Triumph', 'Speed Triple'),
    ('Triumph', 'Speed Triple 1050'),
    ('Triumph', 'Speed Triple 1050R'),
    ('Triumph', 'Speed Triple 1200'),
    ('Triumph', 'Speed Triple 1200 RR'),
    ('Triumph', 'Speed Triple 1200 RS'),
    ('Triumph', 'Speed Triple 1200 RX'),
    ('Triumph', 'Speed Triple R'),
    ('Triumph', 'Speed Triple RS'),
    ('Triumph', 'Speed Triple S'),
    ('Triumph', 'Speed Twin'),
    ('Triumph', 'Speed Twin 1200'),
    ('Triumph', 'Speed Twin 900'),
    ('Triumph', 'SpeedMaster'),
    ('Triumph', 'Speedmaster 900'),
    ('Triumph', 'Sprint'),
    ('Triumph', 'Sprint RS'),
    ('Triumph', 'Sprint ST'),
    ('Triumph', 'Street Cup'),
    ('Triumph', 'Street Scrambler'),
    ('Triumph', 'Street Triple'),
    ('Triumph', 'Street Triple Moto2 Edition'),
    ('Triumph', 'Street Triple Moto2TM Edition'),
    ('Triumph', 'Street Triple R'),
    ('Triumph', 'Street Triple RS'),
    ('Triumph', 'Street Triple S'),
    ('Triumph', 'Street Twin'),
    ('Triumph', 'Street Twin 900'),
    ('Triumph', 'TF250-X'),
    ('Triumph', 'TF450-RC Edition'),
    ('Triumph', 'TR7'),
    ('Triumph', 'TR8'),
    ('Triumph', 'TRIUMPH TRAILERS'),
    ('Triumph', 'TT600'),
    ('Triumph', 'Thruxton'),
    ('Triumph', 'Thruxton 1200'),
    ('Triumph', 'Thruxton 1200R'),
    ('Triumph', 'Thruxton 400'),
    ('Triumph', 'Thruxton R'),
    ('Triumph', 'Thruxton RS'),
    ('Triumph', 'Thunderbird'),
    ('Triumph', 'Thunderbird Commander'),
    ('Triumph', 'Thunderbird LT'),
    ('Triumph', 'Thunderbird Storm'),
    ('Triumph', 'Tiger'),
    ('Triumph', 'Tiger 1200'),
    ('Triumph', 'Tiger 1200 GT'),
    ('Triumph', 'Tiger 1200 Rally'),
    ('Triumph', 'Tiger 800'),
    ('Triumph', 'Tiger 850 Sport'),
    ('Triumph', 'Tiger 900'),
    ('Triumph', 'Tiger 900 GT'),
    ('Triumph', 'Tiger 900 Rally'),
    ('Triumph', 'Tiger Sport'),
    ('Triumph', 'Tiger Sport 660'),
    ('Triumph', 'Tiger Sport 800'),
    ('Triumph', 'Tracker 400'),
    ('Triumph', 'Trident'),
    ('Triumph', 'Trident 660'),
    ('Triumph', 'Trident 750'),
    ('Triumph', 'Trident 800'),
    ('Triumph', 'Trident 900'),
    ('Triumph', 'Trophy'),
    ('Triumph', 'Trophy 1200'),
    ('Triumph', 'Trophy 900'),
    ('Great Wall (GWM)', 'Hover'),
    ('Great Wall (GWM)', 'Hover H3'),
    ('Great Wall (GWM)', 'Hover H5'),
    ('Great Wall (GWM)', 'Wingle 5'),
    ('Great Wall (GWM)', 'Wingle 7'),
    ('Great Wall (GWM)', 'Poer'),
    ('Great Wall (GWM)', 'Safe'),
    ('Great Wall (GWM)', 'Deer'),
    ('Great Wall (GWM)', 'Pegasus'),
    ('IZH (ИЖ)', '2126 Ода'),
    ('IZH (ИЖ)', '2717'),
    ('IZH (ИЖ)', '412'),
    ('IZH (ИЖ)', '2125 Комби'),
    ('IZH (ИЖ)', '21251'),
    ('Mercury', 'Capri'),
    ('Mercury', 'Cougar'),
    ('Mercury', 'Grand Marquis'),
    ('Mercury', 'Lynx'),
    ('Mercury', 'MARQUIS'),
    ('Mercury', 'Marauder'),
    ('Mercury', 'Mariner'),
    ('Mercury', 'Milan'),
    ('Mercury', 'Montego'),
    ('Mercury', 'Monterey'),
    ('Mercury', 'Mountaineer'),
    ('Mercury', 'Mystique'),
    ('Mercury', 'Sable'),
    ('Mercury', 'Topaz'),
    ('Mercury', 'Tracer'),
    ('Mercury', 'Villager'),
    ('Mercury', 'Zephyr'),
    ('Citroen', 'Berlingo'),
    ('Citroen', 'C-Crosser'),
    ('Citroen', 'C-Elissée'),
    ('Citroen', 'C-Zero'),
    ('Citroen', 'C1'),
    ('Citroen', 'C2'),
    ('Citroen', 'C3'),
    ('Citroen', 'C3 Picasso'),
    ('Citroen', 'C4'),
    ('Citroen', 'C4 Aircross'),
    ('Citroen', 'C4 Cactus'),
    ('Citroen', 'C4 Coupé'),
    ('Citroen', 'C4 Grand Picasso'),
    ('Citroen', 'C4 Sedan'),
    ('Citroen', 'C5'),
    ('Citroen', 'C5 Break'),
    ('Citroen', 'C5 Tourer'),
    ('Citroen', 'C6'),
    ('Citroen', 'C8'),
    ('Citroen', 'DS3'),
    ('Citroen', 'DS4'),
    ('Citroen', 'DS5'),
    ('Citroen', 'Evasion'),
    ('Citroen', 'Jumper'),
    ('Citroen', 'Jumpy'),
    ('Citroen', 'Saxo'),
    ('Citroen', 'Nemo'),
    ('Citroen', 'Xantia'),
    ('Citroen', 'Xsara'),
    ('Iran Khodro', 'Samand'),
    ('Iran Khodro', 'Dena'),
    ('Iran Khodro', 'Runna'),
    ('Iran Khodro', 'Soren'),
    ('Iran Khodro', 'Peugeot Pars'),
    ('Iran Khodro', 'Tara'),
    ('Iran Khodro', 'Arisun'),
    ('Xpeng', 'P5'),
    ('Xpeng', 'P7'),
    ('Xpeng', 'P7i'),
    ('Xpeng', 'G3'),
    ('Xpeng', 'G6'),
    ('Xpeng', 'G9'),
    ('Xpeng', 'X9'),
    ('Livan', 'Sullivan''s Garage'),
    ('Livan', 'Sullivans Motorcycles'),
    ('iCar', 'Basoglu Karavan Sanayi ve Ticaret A.S.'),
    ('iCar', 'ICART EV LLC'),
    ('iCar', 'Miller'),
    ('iCar', 'Santa Barbara'),
    ('iCar', 'Snowblast-Sicard, Inc.'),
    ('iCar', 'TECAM MAKINA OTOMOTIV TEKSTIL CADIR INSAAT ENERJI DIS TICARET'),
    ('iCar', 'Tricargo'),
    ('Jaguar', 'Daimler'),
    ('Jaguar', 'F-Pace'),
    ('Jaguar', 'F-Type'),
    ('Jaguar', 'S-Type'),
    ('Jaguar', 'Sovereign'),
    ('Jaguar', 'X-Type'),
    ('Jaguar', 'X-type Estate'),
    ('Jaguar', 'XE'),
    ('Jaguar', 'XF'),
    ('Jaguar', 'XJ'),
    ('Jaguar', 'XJ12'),
    ('Jaguar', 'XJ6'),
    ('Jaguar', 'XJ8'),
    ('Jaguar', 'XJR'),
    ('Jaguar', 'XK'),
    ('Jaguar', 'XK8 Convertible'),
    ('Jaguar', 'XKR'),
    ('Jaguar', 'XKR Convertible'),
    ('Ravon', 'Nexia R3'),
    ('Ravon', 'Gentra'),
    ('Ravon', 'R2'),
    ('Ravon', 'R4'),
    ('Ravon', 'Matiz'),
    ('Maserati', '228'),
    ('Maserati', '430'),
    ('Maserati', 'Biturbo'),
    ('Maserati', 'Coupe'),
    ('Maserati', 'Ghibli'),
    ('Maserati', 'Grancabrio'),
    ('Maserati', 'Granturismo'),
    ('Maserati', 'Grecale'),
    ('Maserati', 'Levante'),
    ('Maserati', 'MC20'),
    ('Maserati', 'MCPura'),
    ('Maserati', 'Merak'),
    ('Maserati', 'Quattroporte'),
    ('Maserati', 'Spyder'),
    ('Maserati', 'TC'),
    ('Genesis', 'Envy'),
    ('Genesis', 'G70'),
    ('Genesis', 'G80'),
    ('Genesis', 'G90'),
    ('Genesis', 'GV60'),
    ('Genesis', 'GV60 Magma'),
    ('Genesis', 'GV70'),
    ('Genesis', 'GV80'),
    ('Genesis', 'Genesis Supreme'),
    ('Genesis', 'Genesis Trailers Inc.'),
    ('Genesis', 'Supreme'),
    ('Genesis', 'Tahoe'),
    ('Genesis', 'Vortex'),
    ('Lifan', 'Solano'),
    ('Lifan', 'X50'),
    ('Lifan', 'X60'),
    ('Lifan', 'X70'),
    ('Lifan', 'Breez'),
    ('Lifan', 'Smily'),
    ('Lifan', 'Myway'),
    ('Lifan', 'Cebrium'),
    ('CheryExeed', 'TXL'),
    ('CheryExeed', 'LX'),
    ('CheryExeed', 'VX'),
    ('CheryExeed', 'RX'),
    ('CheryExeed', 'ET'),
    ('CMC', 'CYGNUS MANUFACTURING COMPANY (CMC)'),
    ('CMC', 'Cabrillo King'),
    ('CMC', 'Captain America'),
    ('CMC', 'Diablo'),
    ('CMC', 'Popper Chopper'),
    ('CMC', 'Rocket 88'),
    ('CMC', 'Stingrey'),
    ('CMC', 'The Billy Bike'),
    ('CMC', 'Vaquero'),
    ('CMC', 'Ventana'),
    ('Aion', 'S'),
    ('Aion', 'S Plus'),
    ('Aion', 'Y'),
    ('Aion', 'Y Plus'),
    ('Aion', 'V'),
    ('Aion', 'LX'),
    ('Aion', 'ES'),
    ('MINI', 'Cooper'),
    ('MINI', 'Cooper Cabrio'),
    ('MINI', 'Cooper Clubman'),
    ('MINI', 'Cooper D'),
    ('MINI', 'Cooper D Clubman'),
    ('MINI', 'Cooper S'),
    ('MINI', 'Cooper S Cabrio'),
    ('MINI', 'Cooper S Clubman'),
    ('MINI', 'Countryman'),
    ('MINI', 'Mini One'),
    ('MINI', 'One D'),
    ('GAC', 'GS3'),
    ('GAC', 'GS4'),
    ('GAC', 'GS5'),
    ('GAC', 'GS8'),
    ('GAC', 'GA4'),
    ('GAC', 'GA6'),
    ('GAC', 'M8'),
    ('Denza', 'D9'),
    ('Denza', 'N7'),
    ('Denza', 'N8'),
    ('Denza', 'N9'),
    ('Denza', 'Z9'),
    ('Haval', 'Jolion'),
    ('Haval', 'F7'),
    ('Haval', 'F7x'),
    ('Haval', 'H6'),
    ('Haval', 'H9'),
    ('Haval', 'Dargo'),
    ('Haval', 'Dargo X'),
    ('Haval', 'M6'),
    ('Haval', 'H3'),
    ('Haval', 'H5'),
    ('ZX', 'Admiral'),
    ('ZX', 'Grandtiger'),
    ('ZX', 'Landmark'),
    ('Saipa', 'Pride'),
    ('Saipa', 'Tiba'),
    ('Saipa', 'Saina'),
    ('Saipa', 'Quik'),
    ('Saipa', 'Shahin'),
    ('Saipa', '111'),
    ('Saipa', '131'),
    ('Saipa', '132'),
    ('Pontiac', '6000'),
    ('Pontiac', 'Acadian'),
    ('Pontiac', 'Aztek'),
    ('Pontiac', 'Bonneville'),
    ('Pontiac', 'Catalina'),
    ('Pontiac', 'Fiero'),
    ('Pontiac', 'Firebird'),
    ('Pontiac', 'Firefly'),
    ('Pontiac', 'G3'),
    ('Pontiac', 'G5'),
    ('Pontiac', 'G6'),
    ('Pontiac', 'G8'),
    ('Pontiac', 'GTO'),
    ('Pontiac', 'Grand AM'),
    ('Pontiac', 'Grand Lemans'),
    ('Pontiac', 'Grand Prix'),
    ('Pontiac', 'J2000'),
    ('Pontiac', 'Laurentian'),
    ('Pontiac', 'Lemans'),
    ('Pontiac', 'Matiz'),
    ('Pontiac', 'Montana'),
    ('Pontiac', 'Montana SV6'),
    ('Pontiac', 'Parisienne'),
    ('Pontiac', 'Phoenix'),
    ('Pontiac', 'Pursuit'),
    ('Pontiac', 'Safari'),
    ('Pontiac', 'Solstice'),
    ('Pontiac', 'Sunbird'),
    ('Pontiac', 'Sunbird 2000'),
    ('Pontiac', 'Sunburst'),
    ('Pontiac', 'Sunfire'),
    ('Pontiac', 'T1000'),
    ('Pontiac', 'Tempest'),
    ('Pontiac', 'Torrent'),
    ('Pontiac', 'Trans Sport'),
    ('Pontiac', 'Vibe'),
    ('Pontiac', 'Wave'),
    ('GMC', 'ACL'),
    ('GMC', 'ACM'),
    ('GMC', 'AT'),
    ('GMC', 'Acadia'),
    ('GMC', 'Aluminum Tilt'),
    ('GMC', 'Articulated Coach'),
    ('GMC', 'B7'),
    ('GMC', 'C/K Pickup'),
    ('GMC', 'C4'),
    ('GMC', 'C5'),
    ('GMC', 'C6'),
    ('GMC', 'C7'),
    ('GMC', 'C8'),
    ('GMC', 'CACL'),
    ('GMC', 'CNR'),
    ('GMC', 'CWG'),
    ('GMC', 'Caballero'),
    ('GMC', 'Canyon'),
    ('GMC', 'Cruise Origin AV'),
    ('GMC', 'D7'),
    ('GMC', 'DK'),
    ('GMC', 'DS'),
    ('GMC', 'Electric Vehicle'),
    ('GMC', 'Envoy'),
    ('GMC', 'FE'),
    ('GMC', 'Forward Control'),
    ('GMC', 'GMT-400'),
    ('GMC', 'Geo Tracker'),
    ('GMC', 'Heavy Conventional'),
    ('GMC', 'Hi-Cube'),
    ('GMC', 'Hummer EV Pickup'),
    ('GMC', 'Hummer EV SUV'),
    ('GMC', 'Jimmy'),
    ('GMC', 'Jimmy Utility'),
    ('GMC', 'Magna Van'),
    ('GMC', 'NE'),
    ('GMC', 'NR'),
    ('GMC', 'P Truck Forward'),
    ('GMC', 'P6S'),
    ('GMC', 'R Conventional'),
    ('GMC', 'Rally'),
    ('GMC', 'S15 Pickup'),
    ('GMC', 'S15 Utility'),
    ('GMC', 'S6'),
    ('GMC', 'S7'),
    ('GMC', 'Safari'),
    ('GMC', 'Savana'),
    ('GMC', 'Sierra'),
    ('GMC', 'Sierra HD'),
    ('GMC', 'Sierra Limited'),
    ('GMC', 'Sonoma'),
    ('GMC', 'Suburban'),
    ('GMC', 'T-Series'),
    ('GMC', 'Terrain'),
    ('GMC', 'Transit Coach'),
    ('GMC', 'Typhoon'),
    ('GMC', 'V Conventional'),
    ('GMC', 'Value Van'),
    ('GMC', 'Vandura'),
    ('GMC', 'W3'),
    ('GMC', 'W3500/W4500'),
    ('GMC', 'W4'),
    ('GMC', 'W5'),
    ('GMC', 'W5500/W5500 HD'),
    ('GMC', 'W6'),
    ('GMC', 'W7'),
    ('GMC', 'WB'),
    ('GMC', 'WCA'),
    ('GMC', 'WCL'),
    ('GMC', 'WCM'),
    ('GMC', 'WCS'),
    ('GMC', 'WHEB'),
    ('GMC', 'WHL'),
    ('GMC', 'WHLB'),
    ('GMC', 'WHM'),
    ('GMC', 'WHR'),
    ('GMC', 'WHS'),
    ('GMC', 'WIA'),
    ('GMC', 'WIL'),
    ('GMC', 'WIM'),
    ('GMC', 'WIS'),
    ('GMC', 'Yukon'),
    ('GMC', 'Yukon XL'),
    ('Jetour', 'X70'),
    ('Jetour', 'X70 Plus'),
    ('Jetour', 'X90'),
    ('Jetour', 'X95'),
    ('Jetour', 'Dashing'),
    ('Jetour', 'T2'),
    ('Jetour', 'X50'),
    ('Saab', '9-3'),
    ('Saab', '9-3 Cabriolet'),
    ('Saab', '9-3 Coupé'),
    ('Saab', '9-3 SportCombi'),
    ('Saab', '9-5'),
    ('Saab', '9-5 SportCombi'),
    ('Saab', '900'),
    ('Saab', '900 C'),
    ('Saab', '900 C Turbo'),
    ('Saab', '9000'),
    ('Arcfox', 'Alpha S'),
    ('Arcfox', 'Alpha T'),
    ('Arcfox', 'Alpha S5'),
    ('Arcfox', 'Kaola'),
    ('ErAZ', '762'),
    ('ErAZ', '3730'),
    ('Datsun', 'on-DO'),
    ('Datsun', 'mi-DO'),
    ('Datsun', 'GO'),
    ('Datsun', 'GO+'),
    ('Hongqi', 'H5'),
    ('Hongqi', 'H9'),
    ('Hongqi', 'HS5'),
    ('Hongqi', 'HS7'),
    ('Hongqi', 'E-HS9'),
    ('Hongqi', 'E-QM5'),
    ('Polestar', '1'),
    ('Polestar', '2'),
    ('Polestar', '3'),
    ('Polestar', '4'),
    ('Willys', 'MB'),
    ('Willys', 'CJ-2A'),
    ('Willys', 'CJ-3B'),
    ('Willys', 'CJ-5'),
    ('Willys', 'Jeepster'),
    ('Willys', 'Station Wagon'),
    ('Renault Samsung', 'SM3'),
    ('Renault Samsung', 'SM5'),
    ('Renault Samsung', 'SM6'),
    ('Renault Samsung', 'SM7'),
    ('Renault Samsung', 'QM3'),
    ('Renault Samsung', 'QM5'),
    ('Renault Samsung', 'QM6'),
    ('Renault Samsung', 'XM3'),
    ('Bentley', 'A Smith GT Bentley'),
    ('Bentley', 'ARMOURED ARNAGE'),
    ('Bentley', 'Arnage'),
    ('Bentley', 'Azure'),
    ('Bentley', 'Bentayga'),
    ('Bentley', 'Bentley Industries, LLC'),
    ('Bentley', 'Bentley Trailers & Custom Coaches'),
    ('Bentley', 'Brooklands'),
    ('Bentley', 'Continental'),
    ('Bentley', 'Eight'),
    ('Bentley', 'Flying Spur'),
    ('Bentley', 'Mulsanne'),
    ('Bentley', 'Roll Royce Silver Seraph'),
    ('Bentley', 'Rolls-Royce Park Ward'),
    ('Bentley', 'Turbo'),
    ('Infiniti', 'EX'),
    ('Infiniti', 'FX'),
    ('Infiniti', 'G'),
    ('Infiniti', 'G Coupé'),
    ('Infiniti', 'M'),
    ('Infiniti', 'Q'),
    ('Infiniti', 'QX'),
    ('Lincoln', 'Aviator'),
    ('Lincoln', 'Blackwood'),
    ('Lincoln', 'Continental'),
    ('Lincoln', 'Corsair'),
    ('Lincoln', 'LS'),
    ('Lincoln', 'MKC'),
    ('Lincoln', 'MKS'),
    ('Lincoln', 'MKT'),
    ('Lincoln', 'MKX'),
    ('Lincoln', 'MKZ'),
    ('Lincoln', 'Mark'),
    ('Lincoln', 'Mark LT'),
    ('Lincoln', 'Nautilus'),
    ('Lincoln', 'Navigator'),
    ('Lincoln', 'Navigator L'),
    ('Lincoln', 'Town Car'),
    ('Lincoln', 'Zephyr'),
    ('Renault', 'Captur'),
    ('Renault', 'Clio'),
    ('Renault', 'Clio Grandtour'),
    ('Renault', 'Espace'),
    ('Renault', 'Express'),
    ('Renault', 'Fluence'),
    ('Renault', 'Grand Espace'),
    ('Renault', 'Grand Modus'),
    ('Renault', 'Grand Scenic'),
    ('Renault', 'Kadjar'),
    ('Renault', 'Kangoo'),
    ('Renault', 'Kangoo Express'),
    ('Renault', 'Koleos'),
    ('Renault', 'Laguna'),
    ('Renault', 'Laguna Grandtour'),
    ('Renault', 'Latitude'),
    ('Renault', 'Mascott'),
    ('Renault', 'Mégane'),
    ('Renault', 'Mégane CC'),
    ('Renault', 'Mégane Combi'),
    ('Renault', 'Mégane Grandtour'),
    ('Renault', 'Mégane Coupé'),
    ('Renault', 'Mégane Scénic'),
    ('Renault', 'Scénic'),
    ('Renault', 'Talisman'),
    ('Renault', 'Talisman Grandtour'),
    ('Renault', 'Thalia'),
    ('Renault', 'Twingo'),
    ('Renault', 'Wind'),
    ('Renault', 'Zoé'),
    ('Dodge', 'Avenger'),
    ('Dodge', 'Caliber'),
    ('Dodge', 'Challenger'),
    ('Dodge', 'Charger'),
    ('Dodge', 'Grand Caravan'),
    ('Dodge', 'Journey'),
    ('Dodge', 'Magnum'),
    ('Dodge', 'Nitro'),
    ('Dodge', 'RAM'),
    ('Dodge', 'Stealth'),
    ('Dodge', 'Viper'),
    ('Maxus', 'T60'),
    ('Maxus', 'T70'),
    ('Maxus', 'T90'),
    ('Maxus', 'D90'),
    ('Maxus', 'D60'),
    ('Maxus', 'G10'),
    ('Maxus', 'G20'),
    ('Maxus', 'V80'),
    ('Rox', 'MOKE'),
    ('Rox', 'OKA Box Van'),
    ('Rox', 'OKA Cabrio'),
    ('Rox', 'OKA Cargo'),
    ('Rox', 'OKA City'),
    ('Rox', 'OKA Pick Up'),
    ('Rox', 'TROXUS'),
    ('Rox', 'Troxell Company'),
    ('Rox', 'ZROX EV, INC.'),
    ('Rivian', 'R1T'),
    ('Rivian', 'R1S'),
    ('Rivian', 'R2'),
    ('DongFeng', 'AX7'),
    ('DongFeng', 'AX4'),
    ('DongFeng', 'S30'),
    ('DongFeng', 'H30'),
    ('DongFeng', 'Rich 6'),
    ('DongFeng', 'Glory 580'),
    ('Chrysler', '300 C'),
    ('Chrysler', '300 C Touring'),
    ('Chrysler', '300 M'),
    ('Chrysler', 'Crossfire'),
    ('Chrysler', 'Grand Voyager'),
    ('Chrysler', 'LHS'),
    ('Chrysler', 'Neon'),
    ('Chrysler', 'Pacifica'),
    ('Chrysler', 'Plymouth'),
    ('Chrysler', 'PT Cruiser'),
    ('Chrysler', 'Sebring'),
    ('Chrysler', 'Sebring Convertible'),
    ('Chrysler', 'Stratus'),
    ('Chrysler', 'Stratus Cabrio'),
    ('Chrysler', 'Town & Country'),
    ('Chrysler', 'Voyager'),
    ('LiXiang', 'L6'),
    ('LiXiang', 'L7'),
    ('LiXiang', 'L8'),
    ('LiXiang', 'L9'),
    ('LiXiang', 'One'),
    ('LiXiang', 'Mega'),
    ('Daewoo', 'Espero'),
    ('Daewoo', 'Kalos'),
    ('Daewoo', 'Lacetti'),
    ('Daewoo', 'Lanos'),
    ('Daewoo', 'Leganza'),
    ('Daewoo', 'Lublin'),
    ('Daewoo', 'Matiz'),
    ('Daewoo', 'Nexia'),
    ('Daewoo', 'Nubira'),
    ('Daewoo', 'Nubira kombi'),
    ('Daewoo', 'Racer'),
    ('Daewoo', 'Tacuma'),
    ('Daewoo', 'Tico'),
    ('Daewoo', 'Gentra'),
    ('JMC', 'Vigus'),
    ('JMC', 'Baodian'),
    ('JMC', 'Grand Avenue'),
    ('Volvo', '240'),
    ('Volvo', '340'),
    ('Volvo', '360'),
    ('Volvo', '460'),
    ('Volvo', '850'),
    ('Volvo', '850 kombi'),
    ('Volvo', 'C30'),
    ('Volvo', 'C70'),
    ('Volvo', 'C70 Cabrio'),
    ('Volvo', 'C70 Coupé'),
    ('Volvo', 'S40'),
    ('Volvo', 'S60'),
    ('Volvo', 'S70'),
    ('Volvo', 'S80'),
    ('Volvo', 'S90'),
    ('Volvo', 'V40'),
    ('Volvo', 'V50'),
    ('Volvo', 'V60'),
    ('Volvo', 'V70'),
    ('Volvo', 'V90'),
    ('Volvo', 'XC60'),
    ('Volvo', 'XC70'),
    ('Volvo', 'XC90'),
    ('Omoda', 'C5'),
    ('Omoda', 'S5'),
    ('Omoda', 'S5 GT'),
    ('Omoda', 'C7'),
    ('Omoda', 'E5'),
    ('Roewe', 'RX5'),
    ('Roewe', 'RX3'),
    ('Roewe', 'RX8'),
    ('Roewe', 'i5'),
    ('Roewe', 'i6'),
    ('Roewe', 'Marvel R'),
    ('Roewe', 'Ei5'),
    ('Changan', 'CS35'),
    ('Changan', 'CS35 Plus'),
    ('Changan', 'CS55'),
    ('Changan', 'CS55 Plus'),
    ('Changan', 'CS75'),
    ('Changan', 'CS75 Plus'),
    ('Changan', 'CS85'),
    ('Changan', 'CS95'),
    ('Changan', 'Eado'),
    ('Changan', 'Alsvin'),
    ('Changan', 'UNI-K'),
    ('Changan', 'UNI-T'),
    ('Changan', 'UNI-V'),
    ('Changan', 'Hunter'),
    ('Rover', '200'),
    ('Rover', '214'),
    ('Rover', '218'),
    ('Rover', '25'),
    ('Rover', '400'),
    ('Rover', '414'),
    ('Rover', '416'),
    ('Rover', '620'),
    ('Rover', '75'),
    ('Porsche', '911 Carrera'),
    ('Porsche', '911 Carrera Cabrio'),
    ('Porsche', '911 Targa'),
    ('Porsche', '911 Turbo'),
    ('Porsche', '924'),
    ('Porsche', '944'),
    ('Porsche', '997'),
    ('Porsche', 'Boxster'),
    ('Porsche', 'Cayenne'),
    ('Porsche', 'Cayman'),
    ('Porsche', 'Macan'),
    ('Porsche', 'Panamera'),
    ('Land Rover', '109'),
    ('Land Rover', 'Defender'),
    ('Land Rover', 'Discovery'),
    ('Land Rover', 'Discovery Sport'),
    ('Land Rover', 'Freelander'),
    ('Land Rover', 'Range Rover'),
    ('Land Rover', 'Range Rover Evoque'),
    ('Land Rover', 'Range Rover Sport'),
    ('Avatr', '11'),
    ('Avatr', '12'),
    ('Avatr', '07'),
    ('Mitsuoka', 'Viewt'),
    ('Mitsuoka', 'Orochi'),
    ('Mitsuoka', 'Himiko'),
    ('Mitsuoka', 'Galue'),
    ('Mitsuoka', 'Buddy'),
    ('Mitsuoka', 'Rock Star'),
    ('Acura', 'ADX'),
    ('Acura', 'CL'),
    ('Acura', 'ILX'),
    ('Acura', 'Integra'),
    ('Acura', 'Legend'),
    ('Acura', 'MDX'),
    ('Acura', 'NSX'),
    ('Acura', 'RDX'),
    ('Acura', 'RL'),
    ('Acura', 'RLX'),
    ('Acura', 'RSX'),
    ('Acura', 'SLX'),
    ('Acura', 'TL'),
    ('Acura', 'TLX'),
    ('Acura', 'TSX'),
    ('Acura', 'Vigor'),
    ('Acura', 'ZDX'),
    ('Tesla', 'Cybercab'),
    ('Tesla', 'Cybertruck'),
    ('Tesla', 'Model 3'),
    ('Tesla', 'Model S'),
    ('Tesla', 'Model X'),
    ('Tesla', 'Model Y'),
    ('Tesla', 'Roadster'),
    ('Tesla', 'Semi'),
    ('VinFast', 'VF 3'),
    ('VinFast', 'VF 5'),
    ('VinFast', 'VF 6'),
    ('VinFast', 'VF 7'),
    ('VinFast', 'VF 8'),
    ('VinFast', 'VF 9'),
    ('VinFast', 'Lux A2.0'),
    ('VinFast', 'Lux SA2.0'),
    ('Suzuki', 'Alto'),
    ('Suzuki', 'Baleno'),
    ('Suzuki', 'Baleno kombi'),
    ('Suzuki', 'Grand Vitara'),
    ('Suzuki', 'Grand Vitara XL-7'),
    ('Suzuki', 'Ignis'),
    ('Suzuki', 'Jimny'),
    ('Suzuki', 'Kizashi'),
    ('Suzuki', 'Liana'),
    ('Suzuki', 'Samurai'),
    ('Suzuki', 'Splash'),
    ('Suzuki', 'Swift'),
    ('Suzuki', 'SX4'),
    ('Suzuki', 'SX4 Sedan'),
    ('Suzuki', 'Vitara'),
    ('Suzuki', 'Wagon R+'),
    ('Lancia', 'Flavia'),
    ('Lancia', 'RTL53'),
    ('Lancia', 'Thema'),
    ('Riddara', 'RD6'),
    ('Lamborghini', '147'),
    ('Lamborghini', 'Aventador'),
    ('Lamborghini', 'Diablo'),
    ('Lamborghini', 'Gallardo'),
    ('Lamborghini', 'Huracan'),
    ('Lamborghini', 'Murcielago'),
    ('Lamborghini', 'Revuelto'),
    ('Lamborghini', 'Roadster'),
    ('Lamborghini', 'Temerario'),
    ('Lamborghini', 'URUS'),
    ('LuAZ (ЛуАЗ)', '967'),
    ('LuAZ (ЛуАЗ)', '969'),
    ('LuAZ (ЛуАЗ)', '1301'),
    ('LuAZ (ЛуАЗ)', '1302'),
    ('Scion', 'tC'),
    ('Scion', 'xA'),
    ('Scion', 'xB'),
    ('Scion', 'xD'),
    ('Scion', 'iQ'),
    ('Scion', 'FR-S'),
    ('Scion', 'iM'),
    ('Scion', 'iA'),
    ('ShuangHuan', 'Ceo'),
    ('ShuangHuan', 'Noble'),
    ('ShuangHuan', 'Sceo'),
    ('ZIL (ЗИЛ)', '130'),
    ('ZIL (ЗИЛ)', '131'),
    ('ZIL (ЗИЛ)', '157'),
    ('ZIL (ЗИЛ)', '4331'),
    ('ZIL (ЗИЛ)', '5301 «Бычок»'),
    ('ZIL (ЗИЛ)', '41041'),
    ('Foton', 'Tunland'),
    ('Foton', 'Sauvana'),
    ('Foton', 'View'),
    ('Foton', 'Aumark'),
    ('Foton', 'Ollin'),
    ('Smart', 'Cabrio'),
    ('Smart', 'City-Coupé'),
    ('Smart', 'Compact Pulse'),
    ('Smart', 'Forfour'),
    ('Smart', 'Fortwo cabrio'),
    ('Smart', 'Fortwo coupé'),
    ('Smart', 'Roadster'),
    ('Vauxhall', 'Astra'),
    ('Vauxhall', 'Corsa'),
    ('Vauxhall', 'Insignia'),
    ('Vauxhall', 'Vectra'),
    ('Vauxhall', 'Zafira'),
    ('Vauxhall', 'Mokka'),
    ('Vauxhall', 'Meriva'),
    ('Vauxhall', 'Antara'),
    ('Vauxhall', 'Combo'),
    ('Vauxhall', 'Crossland'),
    ('Vauxhall', 'Grandland'),
    ('Vauxhall', 'Vivaro'),
    ('Rolls-Royce', 'Phantom'),
    ('Rolls-Royce', 'Ghost'),
    ('Rolls-Royce', 'Wraith'),
    ('Rolls-Royce', 'Dawn'),
    ('Rolls-Royce', 'Cullinan'),
    ('Rolls-Royce', 'Spectre'),
    ('Rolls-Royce', 'Silver Shadow'),
    ('Rolls-Royce', 'Silver Spirit'),
    ('Rolls-Royce', 'Corniche'),
    ('Plymouth', 'Acclaim'),
    ('Plymouth', 'Arrow'),
    ('Plymouth', 'Breeze'),
    ('Plymouth', 'CARAVELLE'),
    ('Plymouth', 'Champ'),
    ('Plymouth', 'Colt'),
    ('Plymouth', 'Conquest'),
    ('Plymouth', 'GRAN FURY'),
    ('Plymouth', 'Grand Voyager'),
    ('Plymouth', 'HORIZON'),
    ('Plymouth', 'Laser'),
    ('Plymouth', 'Neon'),
    ('Plymouth', 'Prowler'),
    ('Plymouth', 'Reliant'),
    ('Plymouth', 'Sapporo'),
    ('Plymouth', 'Scamp'),
    ('Plymouth', 'Sundance'),
    ('Plymouth', 'TURISMO'),
    ('Plymouth', 'Trailduster'),
    ('Plymouth', 'Voyager'),
    ('Dacia', 'Dokker'),
    ('Dacia', 'Duster'),
    ('Dacia', 'Lodgy'),
    ('Dacia', 'Logan'),
    ('Dacia', 'Logan MCV'),
    ('Dacia', 'Logan Van'),
    ('Dacia', 'Sandero'),
    ('Dacia', 'Solenza'),
    ('Alfa Romeo', '145'),
    ('Alfa Romeo', '146'),
    ('Alfa Romeo', '147'),
    ('Alfa Romeo', '155'),
    ('Alfa Romeo', '156'),
    ('Alfa Romeo', '156 Sportwagon'),
    ('Alfa Romeo', '159'),
    ('Alfa Romeo', '159 Sportwagon'),
    ('Alfa Romeo', '164'),
    ('Alfa Romeo', '166'),
    ('Alfa Romeo', '4C'),
    ('Alfa Romeo', 'Brera'),
    ('Alfa Romeo', 'GTV'),
    ('Alfa Romeo', 'MiTo'),
    ('Alfa Romeo', 'Crosswagon'),
    ('Alfa Romeo', 'Spider'),
    ('Alfa Romeo', 'GT'),
    ('Alfa Romeo', 'Giulietta'),
    ('Alfa Romeo', 'Giulia'),
    ('Skywell', 'ET5'),
    ('Skywell', 'HT-i'),
    ('RAM', '1000'),
    ('RAM', '1225U'),
    ('RAM', '1500'),
    ('RAM', '166U'),
    ('RAM', '2000'),
    ('RAM', '203'),
    ('RAM', '206U'),
    ('RAM', '214'),
    ('RAM', '2235'),
    ('RAM', '234'),
    ('RAM', '2500'),
    ('RAM', '2600'),
    ('RAM', '266'),
    ('RAM', '288'),
    ('RAM', '3000'),
    ('RAM', '307'),
    ('RAM', '3500'),
    ('RAM', '3510'),
    ('RAM', '3600'),
    ('RAM', '4000'),
    ('RAM', '4500'),
    ('RAM', '512'),
    ('RAM', '52'),
    ('RAM', '5500'),
    ('RAM', '612U'),
    ('RAM', '625U'),
    ('RAM', '62U'),
    ('RAM', '725'),
    ('RAM', '825U'),
    ('RAM', '83'),
    ('RAM', '835'),
    ('RAM', '83U'),
    ('RAM', '925'),
    ('RAM', 'B17 Bomber'),
    ('RAM', 'B29 Super Fortress'),
    ('RAM', 'Best Lane Enterprises dba Ramp Free'),
    ('RAM', 'Brammo Street Bikes'),
    ('RAM', 'Burkett''s Autorama'),
    ('RAM', 'CP102B'),
    ('RAM', 'CP80B'),
    ('RAM', 'CP90B'),
    ('RAM', 'Chopper'),
    ('RAM', 'Cruiser'),
    ('RAM', 'Dual Sport'),
    ('RAM', 'EZR'),
    ('RAM', 'EZTRJ'),
    ('RAM', 'EZWR'),
    ('RAM', 'Easton Custom L.L.C'),
    ('RAM', 'EnduraMax'),
    ('RAM', 'FATT HOGG FRAMES'),
    ('RAM', 'FRAMTRAC MANUFACTURING CO. LTD'),
    ('RAM', 'Faith'),
    ('RAM', 'Framar'),
    ('RAM', 'HX-1000'),
    ('RAM', 'HX-2000'),
    ('RAM', 'HX-3000'),
    ('RAM', 'Holiday Rambler'),
    ('RAM', 'JR RAMIRO'),
    ('RAM', 'JSR'),
    ('RAM', 'John Ingram, Inc.'),
    ('RAM', 'KTM Aluminum Frame'),
    ('RAM', 'KTM Steel Frame'),
    ('RAM', 'Kramo Trailers'),
    ('RAM', 'LXR'),
    ('RAM', 'Metro Tram'),
    ('RAM', 'NEXGEN FRAMING SYSTEM, LLC'),
    ('RAM', 'P38 Lightning'),
    ('RAM', 'P40 Warhawk'),
    ('RAM', 'P47 Thunderbird'),
    ('RAM', 'P51 Mustang'),
    ('RAM', 'P63 King Cobra'),
    ('RAM', 'Paramount Custom Cycles'),
    ('RAM', 'PortAFrame'),
    ('RAM', 'ProMaster 1500'),
    ('RAM', 'ProMaster 2500'),
    ('RAM', 'ProMaster 3500'),
    ('RAM', 'Promaster City'),
    ('RAM', 'Protorype'),
    ('RAM', 'Pyramid Manufacturing Co. Trailer'),
    ('RAM', 'RAMP AGE TRAILER CO.'),
    ('RAM', 'RAMSA'),
    ('RAM', 'RAMSHORN WELDING'),
    ('RAM', 'ROAD TRAMPS MC'),
    ('RAM', 'Ram Enterprises, LLC'),
    ('RAM', 'Ram Fabrication'),
    ('RAM', 'Ram Transcorp'),
    ('RAM', 'Rambler'),
    ('RAM', 'Ramika Industries Trailer'),
    ('RAM', 'Ramirez Trailer'),
    ('RAM', 'Ramp Champ'),
    ('RAM', 'Rampless'),
    ('RAM', 'Rampless Motorcycle Trailers'),
    ('RAM', 'Ramptek Trailers'),
    ('RAM', 'Ramsey Fabrication'),
    ('RAM', 'Replica'),
    ('RAM', 'Robert Allen Mowery Ramco LLC'),
    ('RAM', 'SCHRAMM, INC.'),
    ('RAM', 'Scooter'),
    ('RAM', 'TerraMarc Industries'),
    ('RAM', 'Touring'),
    ('RAM', 'Tram Power Car'),
    ('RAM', 'Tram Trailer'),
    ('RAM', 'Tramont Corporation'),
    ('RAM', 'Tramont Manufacturing LLC'),
    ('RAM', 'Urban'),
    ('RAM', 'WVR'),
    ('RAM', 'YWR'),
    ('RAM', 'YWVR'),
    ('Chevrolet', 'Alero'),
    ('Chevrolet', 'Aveo'),
    ('Chevrolet', 'Camaro'),
    ('Chevrolet', 'Captiva'),
    ('Chevrolet', 'Corvette'),
    ('Chevrolet', 'Cruze'),
    ('Chevrolet', 'Cruze SW'),
    ('Chevrolet', 'Epica'),
    ('Chevrolet', 'Equinox'),
    ('Chevrolet', 'Evanda'),
    ('Chevrolet', 'HHR'),
    ('Chevrolet', 'Kalos'),
    ('Chevrolet', 'Lacetti'),
    ('Chevrolet', 'Lacetti SW'),
    ('Chevrolet', 'Lumina'),
    ('Chevrolet', 'Malibu'),
    ('Chevrolet', 'Matiz'),
    ('Chevrolet', 'Monte Carlo'),
    ('Chevrolet', 'Nubira'),
    ('Chevrolet', 'Orlando'),
    ('Chevrolet', 'Spark'),
    ('Chevrolet', 'Suburban'),
    ('Chevrolet', 'Tacuma'),
    ('Chevrolet', 'Tahoe'),
    ('Chevrolet', 'Trax'),
    ('SMZ', 'С3А'),
    ('SMZ', 'С3Д'),
    ('Daihatsu', 'Charade'),
    ('Daihatsu', 'Low Speed Vehicle'),
    ('Daihatsu', 'Rocky'),
    ('Buick', 'Allure'),
    ('Buick', 'Cascada'),
    ('Buick', 'Century'),
    ('Buick', 'Coachbuilder'),
    ('Buick', 'Electra'),
    ('Buick', 'Enclave'),
    ('Buick', 'Encore'),
    ('Buick', 'Encore GX'),
    ('Buick', 'Envision'),
    ('Buick', 'Envista'),
    ('Buick', 'LaCrosse'),
    ('Buick', 'LeSabre'),
    ('Buick', 'Lucerne'),
    ('Buick', 'Park Avenue'),
    ('Buick', 'Rainier'),
    ('Buick', 'Reatta'),
    ('Buick', 'Regal'),
    ('Buick', 'Regal TourX'),
    ('Buick', 'Rendezvous'),
    ('Buick', 'Riviera'),
    ('Buick', 'Roadmaster'),
    ('Buick', 'Skyhawk'),
    ('Buick', 'Skylark'),
    ('Buick', 'Somerset'),
    ('Buick', 'Terraza'),
    ('Buick', 'Verano'),
    ('DFSK', 'Glory 500'),
    ('DFSK', 'Glory 560'),
    ('DFSK', 'Glory 580'),
    ('DFSK', 'Glory 600'),
    ('DFSK', 'K01'),
    ('DFSK', 'K05'),
    ('DFSK', 'C31'),
    ('DFSK', 'C37'),
    ('Lotus', '2-Eleven'),
    ('Lotus', '340R'),
    ('Lotus', 'ELETRE'),
    ('Lotus', 'Eagle'),
    ('Lotus', 'Eclat'),
    ('Lotus', 'Elan'),
    ('Lotus', 'Eleven'),
    ('Lotus', 'Elise'),
    ('Lotus', 'Elite'),
    ('Lotus', 'Emira'),
    ('Lotus', 'Esprit'),
    ('Lotus', 'Europa'),
    ('Lotus', 'Evora'),
    ('Lotus', 'Exige'),
    ('Lotus', 'MEL'),
    ('Lotus', 'Monaco'),
    ('Lotus', 'Monza'),
    ('Lotus', 'Spa'),
    ('Lotus', 'Turbo Esprit'),
    ('Chery', 'Tiggo 2'),
    ('Chery', 'Tiggo 3'),
    ('Chery', 'Tiggo 4'),
    ('Chery', 'Tiggo 4 Pro'),
    ('Chery', 'Tiggo 7'),
    ('Chery', 'Tiggo 7 Pro'),
    ('Chery', 'Tiggo 8'),
    ('Chery', 'Tiggo 8 Pro'),
    ('Chery', 'Arrizo 5'),
    ('Chery', 'Arrizo 6'),
    ('Chery', 'Arrizo 8'),
    ('Chery', 'Amulet'),
    ('Chery', 'Fora'),
    ('Chery', 'Kimo'),
    ('Chery', 'QQ'),
    ('Chery', 'Bonus'),
    ('Forthing', 'T5'),
    ('Forthing', 'T5 Evo'),
    ('Forthing', 'Yacht'),
    ('Forthing', 'Friday'),
    ('Forthing', 'S50'),
    ('Jiyue', '01'),
    ('Jiyue', '07'),
    ('McLaren', '540C'),
    ('McLaren', '570GT'),
    ('McLaren', '570S'),
    ('McLaren', '600LT'),
    ('McLaren', '620R'),
    ('McLaren', '625C'),
    ('McLaren', '650S'),
    ('McLaren', '675LT'),
    ('McLaren', '720S'),
    ('McLaren', '750S'),
    ('McLaren', '765LT'),
    ('McLaren', 'ARTURA'),
    ('McLaren', 'ELVA'),
    ('McLaren', 'GT'),
    ('McLaren', 'GTS'),
    ('McLaren', 'Luggage Trailer'),
    ('McLaren', 'MP4-12C'),
    ('McLaren', 'P1'),
    ('McLaren', 'SENNA'),
    ('McLaren', 'SENNA GTR'),
    ('Hozon', 'Neta V'),
    ('Hozon', 'Neta U'),
    ('Hozon', 'Neta S'),
    ('Hozon', 'Neta X'),
    ('Ferrari', '12Cilindri'),
    ('Ferrari', '296'),
    ('Ferrari', '296 Speciale'),
    ('Ferrari', '296 Speciale A'),
    ('Ferrari', '3.2 Mondial'),
    ('Ferrari', '308 Convertible'),
    ('Ferrari', '308GTB'),
    ('Ferrari', '308GTB Quattrovalvole'),
    ('Ferrari', '308GTBi'),
    ('Ferrari', '308GTS'),
    ('Ferrari', '308GTS Quattrovalvole'),
    ('Ferrari', '308GTSi'),
    ('Ferrari', '328'),
    ('Ferrari', '328 GTB'),
    ('Ferrari', '328 GTS'),
    ('Ferrari', '348 Spider'),
    ('Ferrari', '348 tb'),
    ('Ferrari', '348 ts'),
    ('Ferrari', '355 Berlinetta'),
    ('Ferrari', '355 GTS'),
    ('Ferrari', '355 Spider'),
    ('Ferrari', '360'),
    ('Ferrari', '430'),
    ('Ferrari', '456'),
    ('Ferrari', '456M'),
    ('Ferrari', '458'),
    ('Ferrari', '458 Italia'),
    ('Ferrari', '488'),
    ('Ferrari', '512 TR'),
    ('Ferrari', '550 Barchetta'),
    ('Ferrari', '550 Maranello'),
    ('Ferrari', '575M Maranello'),
    ('Ferrari', '599'),
    ('Ferrari', '599 GTB Fiorano'),
    ('Ferrari', '612 Scaglietti'),
    ('Ferrari', '812'),
    ('Ferrari', '849 Testarossa'),
    ('Ferrari', 'Amalfi'),
    ('Ferrari', 'California'),
    ('Ferrari', 'California T'),
    ('Ferrari', 'Challenge Stradale'),
    ('Ferrari', 'Daytona SP3'),
    ('Ferrari', 'Enzo'),
    ('Ferrari', 'F12 Berlinetta'),
    ('Ferrari', 'F12 Special Series'),
    ('Ferrari', 'F12 tdf (Tour de France)'),
    ('Ferrari', 'F355'),
    ('Ferrari', 'F40'),
    ('Ferrari', 'F430'),
    ('Ferrari', 'F50'),
    ('Ferrari', 'F60 America'),
    ('Ferrari', 'F8'),
    ('Ferrari', 'F80'),
    ('Ferrari', 'FF'),
    ('Ferrari', 'GTC4Lusso'),
    ('Ferrari', 'La Ferrari'),
    ('Ferrari', 'Luce'),
    ('Ferrari', 'Mondial 8'),
    ('Ferrari', 'Mondial T'),
    ('Ferrari', 'Monza SP1/SP2'),
    ('Ferrari', 'Portofino'),
    ('Ferrari', 'Portofino M'),
    ('Ferrari', 'Purosangue'),
    ('Ferrari', 'Roma'),
    ('Ferrari', 'SF90'),
    ('Ferrari', 'Testarossa'),
    ('Zeekr', '001'),
    ('Zeekr', '007'),
    ('Zeekr', '009'),
    ('Zeekr', 'X'),
    ('Zeekr', '7X'),
    ('Explorer', 'EXPLORER VAN COMPANY'),
    ('Explorer', 'Explorer Forward Fold'),
    ('Explorer', 'Explorer Rear Fold'),
    ('Xiaomi', 'SU7'),
    ('Xiaomi', 'YU7'),
    ('Derways', 'Cowboy'),
    ('Derways', 'Plutus'),
    ('Derways', 'Shuttle'),
    ('Derways', 'Aurora'),
    ('Derways', 'Land Crown'),
    ('Fisker', 'Karma'),
    ('Fisker', 'Nina'),
    ('Fisker', 'Ocean'),
    ('Skoda', 'Favorit'),
    ('Skoda', 'Felicia'),
    ('Skoda', 'Citigo'),
    ('Skoda', 'Fabia'),
    ('Skoda', 'Fabia Combi'),
    ('Skoda', 'Fabia Sedan'),
    ('Skoda', 'Felicia Combi'),
    ('Skoda', 'Octavia'),
    ('Skoda', 'Octavia Combi'),
    ('Skoda', 'Roomster'),
    ('Skoda', 'Yeti'),
    ('Skoda', 'Rapid'),
    ('Skoda', 'Rapid Spaceback'),
    ('Skoda', 'Superb'),
    ('Skoda', 'Superb Combi'),
    ('Nio', 'ES6'),
    ('Nio', 'ES7'),
    ('Nio', 'ES8'),
    ('Nio', 'EC6'),
    ('Nio', 'EC7'),
    ('Nio', 'ET5'),
    ('Nio', 'ET7'),
    ('Nio', 'ET9'),
    ('ZAZ (ЗАЗ)', 'Таврия'),
    ('ZAZ (ЗАЗ)', 'Славута'),
    ('ZAZ (ЗАЗ)', 'Сенс'),
    ('ZAZ (ЗАЗ)', 'Ланос'),
    ('ZAZ (ЗАЗ)', 'Шанс'),
    ('ZAZ (ЗАЗ)', '968'),
    ('ZAZ (ЗАЗ)', '965'),
    ('ZAZ (ЗАЗ)', '1102'),
    ('Hummer', 'H2'),
    ('Hummer', 'H3'),
    ('Opel', 'Agila'),
    ('Opel', 'Ampera'),
    ('Opel', 'Antara'),
    ('Opel', 'Astra'),
    ('Opel', 'Astra cabrio'),
    ('Opel', 'Astra caravan'),
    ('Opel', 'Astra coupé'),
    ('Opel', 'Calibra'),
    ('Opel', 'Campo'),
    ('Opel', 'Cascada'),
    ('Opel', 'Corsa'),
    ('Opel', 'Frontera'),
    ('Opel', 'Insignia'),
    ('Opel', 'Insignia kombi'),
    ('Opel', 'Kadett'),
    ('Opel', 'Meriva'),
    ('Opel', 'Mokka'),
    ('Opel', 'Movano'),
    ('Opel', 'Omega'),
    ('Opel', 'Signum'),
    ('Opel', 'Vectra'),
    ('Opel', 'Vectra Caravan'),
    ('Opel', 'Vivaro'),
    ('Opel', 'Vivaro Kombi'),
    ('Opel', 'Zafira'),
    ('Abarth', '500'),
    ('Abarth', '595'),
    ('Abarth', '695'),
    ('Abarth', '124 Spider'),
    ('Abarth', 'Punto'),
    ('Abarth', 'Grande Punto'),
    ('Cadillac', '60 Special'),
    ('Cadillac', 'ATS'),
    ('Cadillac', 'Allante'),
    ('Cadillac', 'Armored Vehicle'),
    ('Cadillac', 'Brougham'),
    ('Cadillac', 'CT4'),
    ('Cadillac', 'CT5'),
    ('Cadillac', 'CT6'),
    ('Cadillac', 'CTS'),
    ('Cadillac', 'Catera'),
    ('Cadillac', 'Celestiq'),
    ('Cadillac', 'Cimarron'),
    ('Cadillac', 'DTS'),
    ('Cadillac', 'Deville'),
    ('Cadillac', 'ELR'),
    ('Cadillac', 'Eldorado'),
    ('Cadillac', 'Escalade'),
    ('Cadillac', 'Escalade ESV'),
    ('Cadillac', 'Escalade IQ'),
    ('Cadillac', 'Escalade IQL'),
    ('Cadillac', 'Fleetwood'),
    ('Cadillac', 'Funeral Coach'),
    ('Cadillac', 'Hearse'),
    ('Cadillac', 'Limousine'),
    ('Cadillac', 'Lyriq'),
    ('Cadillac', 'Optiq'),
    ('Cadillac', 'SRX'),
    ('Cadillac', 'STS'),
    ('Cadillac', 'Seville'),
    ('Cadillac', 'Stretch Limousine'),
    ('Cadillac', 'Vistiq'),
    ('Cadillac', 'XLR'),
    ('Cadillac', 'XT4'),
    ('Cadillac', 'XT5'),
    ('Cadillac', 'XT6'),
    ('Cadillac', 'XTS'),
    ('Aito', 'M5'),
    ('Aito', 'M7'),
    ('Aito', 'M9'),
    ('Jeep', 'Cherokee'),
    ('Jeep', 'Commander'),
    ('Jeep', 'Compass'),
    ('Jeep', 'Grand Cherokee'),
    ('Jeep', 'Patriot'),
    ('Jeep', 'Renegade'),
    ('Jeep', 'Wrangler'),
    ('Karry', 'Karry USA Trailers'),
    ('Peugeot', '1007'),
    ('Peugeot', '107'),
    ('Peugeot', '106'),
    ('Peugeot', '108'),
    ('Peugeot', '2008'),
    ('Peugeot', '205'),
    ('Peugeot', '205 Cabrio'),
    ('Peugeot', '206'),
    ('Peugeot', '206 CC'),
    ('Peugeot', '206 SW'),
    ('Peugeot', '207'),
    ('Peugeot', '207 CC'),
    ('Peugeot', '207 SW'),
    ('Peugeot', '306'),
    ('Peugeot', '307'),
    ('Peugeot', '307 CC'),
    ('Peugeot', '307 SW'),
    ('Peugeot', '308'),
    ('Peugeot', '308 CC'),
    ('Peugeot', '308 SW'),
    ('Peugeot', '309'),
    ('Peugeot', '4007'),
    ('Peugeot', '4008'),
    ('Peugeot', '405'),
    ('Peugeot', '406'),
    ('Peugeot', '407'),
    ('Peugeot', '407 SW'),
    ('Peugeot', '5008'),
    ('Peugeot', '508'),
    ('Peugeot', '508 SW'),
    ('Peugeot', '605'),
    ('Peugeot', '806'),
    ('Peugeot', '607'),
    ('Peugeot', '807'),
    ('Peugeot', 'Bipper'),
    ('Peugeot', 'RCZ'),
    ('Oldsmobile', 'Achieva'),
    ('Oldsmobile', 'Alero'),
    ('Oldsmobile', 'Aurora'),
    ('Oldsmobile', 'Bravada'),
    ('Oldsmobile', 'Custom Cruiser'),
    ('Oldsmobile', 'Cutlass'),
    ('Oldsmobile', 'Cutlass Calais'),
    ('Oldsmobile', 'Cutlass Ciera'),
    ('Oldsmobile', 'Cutlass Cruiser'),
    ('Oldsmobile', 'Cutlass Salon'),
    ('Oldsmobile', 'Cutlass Supreme'),
    ('Oldsmobile', 'Delta 88'),
    ('Oldsmobile', 'Eighty Eight (88)'),
    ('Oldsmobile', 'Firenza'),
    ('Oldsmobile', 'Intrigue'),
    ('Oldsmobile', 'LSS'),
    ('Oldsmobile', 'Ninety Eight (98)'),
    ('Oldsmobile', 'Omega'),
    ('Oldsmobile', 'Regency'),
    ('Oldsmobile', 'Silhouette'),
    ('Oldsmobile', 'Toronado'),
    ('Isuzu', '4000 Series Medium Duty'),
    ('Isuzu', '5000 Series Medium Duty'),
    ('Isuzu', '6000 Series Medium Duty'),
    ('Isuzu', '7000 Series Medium Duty'),
    ('Isuzu', 'Amigo'),
    ('Isuzu', 'Ascender'),
    ('Isuzu', 'Axiom'),
    ('Isuzu', 'F6'),
    ('Isuzu', 'F7'),
    ('Isuzu', 'FRR'),
    ('Isuzu', 'FSR'),
    ('Isuzu', 'FTR'),
    ('Isuzu', 'FTR/FVR'),
    ('Isuzu', 'FTR/FVR/EVR'),
    ('Isuzu', 'FVR'),
    ('Isuzu', 'Forward Control'),
    ('Isuzu', 'Forward Control (for walk-in van)'),
    ('Isuzu', 'H-Series'),
    ('Isuzu', 'Hombre'),
    ('Isuzu', 'I-Mark'),
    ('Isuzu', 'IMPULSE'),
    ('Isuzu', 'Medium Front Engine Bus'),
    ('Isuzu', 'Medium Rear Engine Bus'),
    ('Isuzu', 'NPR'),
    ('Isuzu', 'NPR-HD'),
    ('Isuzu', 'NPR-XD'),
    ('Isuzu', 'NPR/NPR-HD'),
    ('Isuzu', 'NQR'),
    ('Isuzu', 'NQR/NRR'),
    ('Isuzu', 'NRR'),
    ('Isuzu', 'Oasis'),
    ('Isuzu', 'Pickup'),
    ('Isuzu', 'REACH'),
    ('Isuzu', 'Rodeo'),
    ('Isuzu', 'Rodeo/Amigo'),
    ('Isuzu', 'Stylus'),
    ('Isuzu', 'T6F'),
    ('Isuzu', 'T7F'),
    ('Isuzu', 'T8F'),
    ('Isuzu', 'Trooper'),
    ('Isuzu', 'Trooper II'),
    ('Isuzu', 'VehiCross'),
    ('Isuzu', 'i-280'),
    ('Isuzu', 'i-290'),
    ('Isuzu', 'i-350'),
    ('Isuzu', 'i-370'),
    ('SsangYong', 'Actyon'),
    ('SsangYong', 'Actyon Sports'),
    ('SsangYong', 'Korando'),
    ('SsangYong', 'Kyron'),
    ('SsangYong', 'Musso'),
    ('SsangYong', 'Rexton'),
    ('SsangYong', 'Rodius'),
    ('SsangYong', 'Tivoli'),
    ('SsangYong', 'Chairman'),
    ('SsangYong', 'Istana'),
    ('Leapmotor', 'C01'),
    ('Leapmotor', 'C10'),
    ('Leapmotor', 'C11'),
    ('Leapmotor', 'C16'),
    ('Leapmotor', 'T03'),
    ('Leapmotor', 'S01'),
    ('Geely', 'Coolray'),
    ('Geely', 'Atlas'),
    ('Geely', 'Atlas Pro'),
    ('Geely', 'Emgrand'),
    ('Geely', 'Emgrand X7'),
    ('Geely', 'Tugella'),
    ('Geely', 'Monjaro'),
    ('Geely', 'Okavango'),
    ('Geely', 'Preface'),
    ('Geely', 'MK'),
    ('Geely', 'CK'),
    ('Geely', 'Vision'),
    ('BYD', 'Song'),
    ('BYD', 'Song Plus'),
    ('BYD', 'Han'),
    ('BYD', 'Tang'),
    ('BYD', 'Qin'),
    ('BYD', 'Qin Plus'),
    ('BYD', 'Seal'),
    ('BYD', 'Seagull'),
    ('BYD', 'Dolphin'),
    ('BYD', 'Atto 3'),
    ('BYD', 'Yuan Plus'),
    ('BYD', 'F3'),
    ('BYD', 'E6'),
    ('Lynk & Co', '01'),
    ('Lynk & Co', '02'),
    ('Lynk & Co', '03'),
    ('Lynk & Co', '05'),
    ('Lynk & Co', '06'),
    ('Lynk & Co', '08'),
    ('Lynk & Co', '09'),
    ('Maextro', 'S800'),
    ('MG', 'CHEMGUARD'),
    ('MG', 'CMG Custom Trailers, Inc.'),
    ('MG', 'Jim Glo Trailers, LLC Trading as Jimglo Trailers (Jim Glo Trailers)'),
    ('MG', 'MGK'),
    ('MG', 'MGM Trailers'),
    ('MG', 'MGS Incorparated'),
    ('MG', 'Miami'),
    ('MG', 'TMG Trailer'),
    ('Nysa', '501'),
    ('Nysa', '521'),
    ('Nysa', '522'),
    ('Luxeed', 'S7'),
    ('Luxeed', 'R7'),
    ('Saturn', 'Astra'),
    ('Saturn', 'Aura'),
    ('Saturn', 'Ion'),
    ('Saturn', 'L200'),
    ('Saturn', 'L300'),
    ('Saturn', 'LS'),
    ('Saturn', 'LS1'),
    ('Saturn', 'LS2'),
    ('Saturn', 'LW1'),
    ('Saturn', 'LW2'),
    ('Saturn', 'LW200'),
    ('Saturn', 'LW300'),
    ('Saturn', 'Outlook'),
    ('Saturn', 'Relay'),
    ('Saturn', 'SATURN2016'),
    ('Saturn', 'SATURN2019'),
    ('Saturn', 'SC1'),
    ('Saturn', 'SC2'),
    ('Saturn', 'SL'),
    ('Saturn', 'SL1'),
    ('Saturn', 'SL2'),
    ('Saturn', 'SL3'),
    ('Saturn', 'SW1'),
    ('Saturn', 'SW2'),
    ('Saturn', 'Saturn Industries'),
    ('Saturn', 'Sky'),
    ('Saturn', 'Vue'),
    ('BAIC', 'BJ40'),
    ('BAIC', 'BJ60'),
    ('BAIC', 'X35'),
    ('BAIC', 'X55'),
    ('BAIC', 'X7'),
    ('BAIC', 'U5 Plus'),
    ('BAIC', 'EU5'),
    ('BAIC', 'EX3')
) AS m (make_name, name)
JOIN car_makes mk ON mk.name = m.make_name
WHERE NOT EXISTS (
    SELECT 1 FROM car_models existing
     WHERE existing.make_id = mk.id
       AND lower(existing.name) = lower(m.name)
);
